name: Ionic Build and Upload

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build for'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Install project dependencies
        run: |
          npm install @angular/cli

      - name: Build Ionic project
        run: ionic build --prod

     
