name: s3 Upload

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build for'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZEDNY72XWKSB3HUT
          aws-secret-access-key: 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
          aws-region: ap-south-1

      - name: Upload build artifacts to S3
        run: aws s3 sync ./images  s3://gateway-mobile/gateway-temp/ --acl private
      - name: Rename gateway-temp to gateway
        run: aws s3 rm s3://gateway-mobile/gateway/ --recursive
